import {gsap} from 'gsap';
import {OllamaClient,ChatMessage,ModelInfo} from '../core/OllamaClient';
import {Store} from '../core/Store';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]||c));
const format=(s:string)=>esc(s).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\n/g,'<br>');
export class App{
 client=new OllamaClient(localStorage.getItem('steller-endpoint')||'http://localhost:11434'); store=new Store(); model=''; messages:ChatMessage[]=[]; sending=false; abort:AbortController|null=null;
 q<T extends Element>(s:string){const e=document.querySelector<T>(s);if(!e)throw new Error(s+' missing');return e}
 async init(){this.bind();this.load();await this.refreshModels();await this.refreshStatus();this.renderHistory();gsap.from('.welcome>*',{y:24,opacity:0,duration:.7,stagger:.06,ease:'power3.out'})}
 bind(){const p=this.q<HTMLTextAreaElement>('#prompt');this.q<HTMLFormElement>('#composer').addEventListener('submit',e=>{e.preventDefault();void this.send(p.value)});p.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void this.send(p.value)}});this.q('#new-chat').addEventListener('click',()=>this.newChat());document.querySelectorAll<HTMLElement>('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{p.value=b.dataset.prompt||'';p.focus()}));this.q<HTMLSelectElement>('#model').addEventListener('change',e=>{this.model=(e.target as HTMLSelectElement).value;localStorage.setItem('steller-model',this.model)});this.q('#settings').addEventListener('click',()=>this.q<HTMLDialogElement>('#settings-dialog').showModal());this.q('#close-settings').addEventListener('click',()=>this.q<HTMLDialogElement>('#settings-dialog').close());this.q('#save-settings').addEventListener('click',()=>this.saveSettings());this.q('#reset-settings').addEventListener('click',()=>{localStorage.removeItem('steller-endpoint');location.reload()});this.q<HTMLInputElement>('#temperature').addEventListener('input',e=>this.q('#temp-value').textContent=(e.target as HTMLInputElement).value);this.q('#mobile-menu').addEventListener('click',()=>document.querySelector('.sidebar')?.classList.toggle('open'))}
 async refreshModels(){const s=this.q<HTMLSelectElement>('#model');try{const models=await this.client.models();if(!models.length){s.innerHTML='<option>No local models</option>';this.status(false,'No models installed');return;}s.innerHTML=models.map((m:ModelInfo)=>'<option value="'+esc(m.name)+'">'+esc(m.name)+'</option>').join('');const saved=localStorage.getItem('steller-model');this.model=(models.some(m=>m.name===saved)?saved:models[0].name)||'';s.value=this.model;this.q('#model-meta').textContent=((models.find(m=>m.name===this.model)?.details?.parameter_size)||'LOCAL').toUpperCase();}catch{ s.innerHTML='<option>Ollama unavailable</option>';this.status(false,'Ollama offline') }}
 async refreshStatus(){this.status(await this.client.health(),'Ollama connected')}
 status(ok:boolean,text:string){const c=this.q('#connection-card');c.classList.toggle('online',ok);c.querySelector('b')!.textContent=text;c.querySelector('small')!.textContent=this.client.endpoint}
 load(){const c=this.store.ensure();this.messages=c.messages;this.renderMessages()}
 newChat(){this.abort?.abort();const c=this.store.newConversation();this.messages=[];this.renderMessages();this.q<HTMLTextAreaElement>('#prompt').focus()}
 renderHistory(){const h=this.q('#history');h.innerHTML=this.store.conversations.map(c=>'<button class="history-item '+(c.id===this.store.activeId?'active':'')+'" data-id="'+c.id+'"><span>'+esc(c.title)+'</span><small>›</small></button>').join('');h.querySelectorAll<HTMLButtonElement>('[data-id]').forEach(b=>b.addEventListener('click',()=>{this.store.activeId=b.dataset.id||null;this.load();this.renderHistory()}))}
 renderMessages(){const chat=this.q('#chat');this.q('#welcome').setAttribute('style',this.messages.length?'display:none':'');chat.innerHTML=this.messages.filter(m=>m.role!=='system').map(m=>'<article class="message '+m.role+'"><div class="avatar">'+(m.role==='user'?'YOU':'✦')+'</div><div class="message-body"><div class="role">'+(m.role==='user'?'YOU':'STELLER')+'</div><div class="content">'+format(m.content)+'</div></div></article>').join('');chat.scrollTop=chat.scrollHeight;this.renderHistory()}
 async send(text:string){if(this.sending||!text.trim()||!this.model)return;this.sending=true;this.abort=new AbortController();const p=this.q<HTMLTextAreaElement>('#prompt');p.value='';this.q('#send').classList.add('busy');this.q('#latency').textContent='THINKING';this.q('#welcome').setAttribute('style','display:none');this.messages.push({role:'user',content:text.trim()});const assistant:ChatMessage={role:'assistant',content:''};this.messages.push(assistant);this.store.setMessages(this.messages);this.renderMessages();const article=this.q('#chat').lastElementChild as HTMLElement;const content=article.querySelector('.content') as HTMLElement;const started=performance.now();try{const system=this.q<HTMLTextAreaElement>('#system-prompt').value;const temp=Number(this.q<HTMLInputElement>('#temperature').value);await this.client.chat(this.model,[{role:'system',content:system},...this.messages],temp,t=>{assistant.content+=t;content.innerHTML=format(assistant.content);this.q('#chat').scrollTop=this.q('#chat').scrollHeight},tokens=>{this.q('#latency').textContent=Math.round(performance.now()-started)+' MS · '+tokens+' TOKENS'} ,this.abort.signal)}catch(e){if((e as Error).name!=='AbortError'){assistant.content='Connection error: '+((e as Error).message||'Could not reach Ollama.');content.innerHTML=format(assistant.content);this.q('#latency').textContent='ERROR'}}finally{this.sending=false;this.abort=null;this.q('#send').classList.remove('busy');this.store.setMessages(this.messages);this.store.rename();this.renderHistory()}}
 saveSettings(){const endpoint=this.q<HTMLInputElement>('#endpoint').value.trim()||'http://localhost:11434';localStorage.setItem('steller-endpoint',endpoint);this.client=new OllamaClient(endpoint);this.q<HTMLDialogElement>('#settings-dialog').close();void this.refreshModels();void this.refreshStatus()}
}
